### ISSUE TITLE
ATTENTION

### ISSUE THREAD

**Issue by Griffin97** [josh1227/RecessionPrediction#1]
Greetings , i was following through your command lines , impressive work . Would you mind assisting by uploading the DJI CSV that you used on line 206 ?  Thanks

**Comment by josh1227** [comment]
Thanks. I have just uploaded the DJI CSV.

**Comment by Griffin97** [comment]
Thank you very very much Sir.

Your timely response is highly appreciated.

Regards
Griffin.
